### ISSUE TITLE
404

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#57] opened 2021-10-24 21:19 UTC
**Product**
Admin Frontend

**Describe the bug**
404 

**To Reproduce**
1. Go to Resources
2. Create a new resource
3. click on the alphanumeric number 

**Expected behavior**
no 404 

**Screenshots**
![image](https://user-images.githubusercontent.com/93096986/138613358-657fc1e6-9f07-491b-90cc-ebe17db9c48f.png)
![image](https://user-images.githubusercontent.com/93096986/138613367-bc2d3498-3b25-4744-a0ce-ac65027232df.png)

**Comment by johanneshochholzer** [comment] 2021-10-27 12:10
![grafik](https://user-images.githubusercontent.com/75273091/139062832-d1de1e88-1da8-417e-9106-50d74534267a.png)
This behaviour is general
See #24

**Comment by johanneshochholzer** [comment] 2021-10-27 13:54
Duplicate of #24

**Closed as completed by johanneshochholzer** 2021-10-27 13:54 UTC
Labels: bug, admin-frontend
