### ISSUE TITLE
Browse doesn't transfer dates to booking engine

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#18] opened 2021-10-11 09:08 UTC
**Product**
Frontend

**Describe the bug**
I search for a room on 13th to 14th October.
I select a room and the date selection is not transferred.

**To Reproduce**
1. Search for a date
2. Select resource
3. On Detail page the date is not shown

**Expected behavior**
The date is transferred to the detail page of the resource. This is not always the case.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/136763136-a3d4ef80-3610-4dad-8932-d174e44151fc.png)

**Comment by ingowonner** [comment] 2021-11-03 11:46
More details to reproduce this:
- Testunterkunft 2 is booked from 21.12 until 23.12
- Start new search from 24.12. until 25.12.
- Testunterkunft 2 will be shown as available in the list
- Click on Testunterkunft 2
- Detail page will open without any prefilled data
- Check availability on detail page. 24.12 is not available! <-- This is the reason why nothing is prefilled. It's not available on selected date.

Potentially fixed by https://github.com/isarwatt/klink-issues/issues/104

**Closed as completed** 2021-11-05 14:53 UTC
Labels: bug, frontend
