### ISSUE TITLE
Unterkunft not listed

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#55] opened 2021-10-24 21:03 UTC
**Product**
Frontend 

**Describe the bug**
G-Appartment (öffentlich) not listed on the overview but found when search with the search functio

**Expected behavior**
as G-Appartment (öffentlich) is confired as visible for all, it should be listed in the overview.

**Comment by johanneshochholzer** [comment] 2021-10-27 12:05
@ingowonner 
This is a visibility issue similar to #3

**Comment by johanneshochholzer** [comment] 2021-10-27 13:52
Duplicate of #3

**Closed as completed by johanneshochholzer** 2021-10-27 13:52 UTC
Labels: bug
