### ISSUE TITLE
Add My bookings page

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#28] opened 2021-10-13 19:17 UTC
**Product**
Frontend

**Describe the bug**
The button "Zu meinen Buchungen" doesn't lead to a page with all bookings.

**To Reproduce**
1. Create a new booking
2. Click on "Zu meinen Buchungen"
3. Nothing happens.

**Expected behavior**
Open page with list of bookings.

**Comment by benediktdertinger** [comment] 2021-10-18 08:50
This is not implemented and therefore not a bug :)

**Comment by johanneshochholzer** [comment] 2021-10-18 15:14
Okay, then please hide the button until it has any function, thanks.
If the my bookings page is coming up soon you can leave the button as it is.

**Comment by benediktdertinger** [comment] 2021-10-19 06:46
Duplicate of https://github.com/isarwatt/klink-issues-public/issues/28

**Closed as completed** 2021-10-19 06:46 UTC
Labels: enhancement
